<a href="https://colab.research.google.com/github/Edward801/-LSN/blob/main/%D0%AD%D0%B4%D1%83%D0%B0%D1%80%D0%B4_%D0%9C%D0%B0%D0%B3%D0%B0%D1%84%D1%83%D1%80%D0%BE%D0%B2%2C_%D0%B3%D1%80_%D0%9C%D0%9F%D0%98%D0%B7_23%2C_(%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B_%D0%B2%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D1%8F).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Библиотека для работы с массивами данных
import numpy as np

In [ ]:
# Функция метода вращений
def rotation_method(A, tol=1e-6):
    n = A.shape[0] # Задание размера матрицы
    max_iterations = 100 * n ** 2 # Максимальное число итераций (100n^2)

    # Поиск максимального внедиагонального элемента матрицы А.
    def find_max_off_diagonal():
        i, j = 0, 1 # Индексы
        max_elem = abs(A[0, 1]) # Инициализация максимального элемента
        for k in range(n): # Поиск Макс. внедиагонального элемента основан на двойном цикле for, который перебирает все элементы матрицы А
            for l in range(n):  # кроме диагональных элементов, и находит максимальное значение
                if k != l and abs(A[k, l]) > max_elem: # исключение диагональных элементов, и если значение abs(A[k, l]) больше макс. элемента
                    max_elem = abs(A[k, l])
                    i, j = k, l
        return i, j, max_elem # Возвращаем индексы элемента i,j и его значение max_elem

    eigenvectors = np.eye(n)
    eigenvalues_history = []
    iterations = 0 # Число итераций
    i, j, max_elem = find_max_off_diagonal()

    while max_elem > tol and iterations < max_iterations:
        if A[i, i] == A[j, j]:
            angle = np.pi / 4
        else:
            tau = 2 * A[i, j] / (A[i, i] - A[j, j])
            angle = np.arctan(tau) / 2

        rotation_matrix = np.eye(n) # единичная матрица
        rotation_matrix[i, i] = rotation_matrix[j, j] = np.cos(angle) # эти значения устанавливаются в cos заначений
        rotation_matrix[i, j] = -np.sin(angle) # устанавливается в -sin(angle)
        rotation_matrix[j, i] = np.sin(angle) # устанавливается в sin(angle)

        A = rotation_matrix.T @ A @ rotation_matrix # Умножение матриц
        eigenvectors = eigenvectors @ rotation_matrix

        eigenvalues_history.append(np.diag(A).copy())

        print(A)
        #print(eigenvectors)

        i, j, max_elem = find_max_off_diagonal()
        iterations += 1 # Счётчик итераций

        print(iterations)

    eigenvalues = np.diag(A)
    return eigenvalues, eigenvectors, np.array(eigenvalues_history)

In [ ]:
# Исходная матрица
A = np.array([
    [-7, -5, -9],
    [-5, 5, 2],
    [-9, 2, 9]
])

In [ ]:
# Вычисление собственных значений и векторов и истории собственных значений
eigenvalues, eigenvectors, history = rotation_method(A)
errors = np.diff(history, axis=0)
max_errors = np.max(np.abs(errors), axis=1)

[[ 3.82165849e+00  7.06686472e-16  8.53992610e+00]
 [ 1.18041613e-15 -1.28216585e+01 -1.03424478e+00]
 [ 8.53992610e+00 -1.03424478e+00 -1.00000000e+00]]
1
[[ 1.02845227e+01 -6.24120783e-01  6.14448168e-16]
 [-6.24120783e-01 -1.28216585e+01 -8.24703289e-01]
 [ 4.64878625e-16 -8.24703289e-01 -7.46286420e+00]]
2
[[ 1.02845227e+01 -6.17178080e-01  9.28330175e-02]
 [-6.17178080e-01 -1.29457065e+01 -1.75296140e-16]
 [ 9.28330175e-02  1.63738593e-16 -7.33881622e+00]]
3
[[ 1.03009082e+01  2.97983386e-17  9.28003178e-02]
 [ 2.25041601e-16 -1.29620920e+01  2.46377043e-03]
 [ 9.28003178e-02  2.46377043e-03 -7.33881622e+00]]
4
[[ 1.03013964e+01  1.29610407e-05 -6.45410271e-18]
 [ 1.29610407e-05 -1.29620920e+01  2.46373634e-03]
 [-2.17437809e-16  2.46373634e-03 -7.33930442e+00]]
5
[[ 1.03013964e+01  1.29610395e-05  5.67913641e-09]
 [ 1.29610395e-05 -1.29620931e+01 -3.33657257e-16]
 [ 5.67913620e-09  5.97331289e-19 -7.33930334e+00]]
6
[[ 1.03013964e+01 -1.93578086e-16  5.67913641e-09]
 [ 8.12027833

In [ ]:
# Вывод собственных значений
print("\nСобственные значения:")
print(eigenvalues)


Собственные значения:
[ 10.30139645 -12.96209311  -7.33930334]


In [ ]:
# Вывод собственных векторов
print("\nСобственные векторы:")
print(eigenvectors)


Собственные векторы:
[[ 0.68601342  0.41377235 -0.59847977]
 [-0.40532144  0.90042945  0.15792826]
 [ 0.60423516  0.13423577  0.78541749]]


In [ ]:
# Вывод количества итераций и погрешности
print("\nКоличество итераций:", len(max_errors))


Количество итераций: 6
